### ISSUE TITLE
Use structured output

### ISSUE THREAD

**Issue by matiaslopezd** [supermomo668/FiCast-GPT#4]
Now is possible to use structured output with Gemini API: https://ai.google.dev/gemini-api/docs/structured-output?lang=python

https://github.com/supermomo668/FiCast-GPT/blob/b6868387f0907b8510ccd6f601470932043c2b84/ficast/conversation/utils.py#L12-L25

**Comment by supermomo668** [comment]
PyAutogen handles the output struct through it's wrapper
